# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bowfolio-yuhan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bowfolio-yuhan
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'Firebase/Analytics'
end
